services:
  go-chatgpt-api:
    container_name: ${APP_NAME}-api
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    environment:
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
      - GO_CHATGPT_API_PANDORA=${API_PANDORA}
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=${ARKOSE_TOKEN_URL}
      - GO_CHATGPT_API_OPENAI_EMAIL=${OPENAI_EMAIL}
      - GO_CHATGPT_API_OPENAI_PASSWORD=${OPENAI_PASSWORD}
    image: linweiyuan/go-chatgpt-api:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    depends_on:
      - chatgpt-proxy-server-warp
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    labels:  
      createdBy: "bt_apps"

  chatgpt-proxy-server-warp:
    container_name: ${APP_NAME}-warp
    restart: always
    networks:
      - baota_net
    image: linweiyuan/chatgpt-proxy-server-warp:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      - LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    labels:  
      createdBy: "bt_apps"
networks:
  baota_net:
    external: true