services:
  v2raya:
    container_name: ${APP_NAME}
    restart: always
    network_mode: "host"
    privileged: true
    environment:
      - V2RAYA_CONFIG:/etc/v2raya
      - V2RAYA_ADDRESS=0.0.0.0:${WEB_PORT}
      - V2RAYA_PLUGINLISTENPORT:${PLUGIN_PORT}
    volumes:
      - "${APP_PATH}/data/v2raya:/etc/v2raya"
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
    image: mzz2017/v2raya:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
