services:
  phtunnel:
    image: "bestoray/phtunnel:1.0.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    devices:
      - /dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      createdBy: "bt_apps"
