services:
  pingvin-share:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3000"
    volumes:
      - "${APP_PATH}/data:/opt/app/backend/data"
      - "${UPLOAD_PATH}:/opt/app/frontend/public/img"
    image: stonith404/pingvin-share:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
