services:
  cloudbeaver:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8978"
    volumes:
      - "${APP_PATH}/data:/opt/cloudbeaver/workspace"
    tty: true
    image: dbeaver/cloudbeaver:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
