services:
  memcached:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:11211"
    command: memcached -m ${MEM_CACHED}
    image: "memcached:1.6.19-alpine3.17"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
networks:  
  baota_net:  
    external: true
