services:
  modstartblog:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - ./data:/server/web
    image: modstart/modstartblog:v8.6.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
