services:
  mcsm-daemon:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:24444"
    volumes:
      - "${APP_PATH}/data:/opt/mcsmanager/daemon/data"
      - /var/run/docker.sock:/var/run/docker.sock
    image: alisaqaq/mcsmanager-daemon:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
