services:
  mosdns:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:53/tcp"
      - "${HOST_IP}:${WEB_PORT}:53/udp"
      - "${HOST_IP}:${PANEL_APP_PORT_API}:8080"
    volumes:
      - "${APP_PATH}/data:/etc/mosdns"
    image: irinesistiana/mosdns:v5.3.3
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true

