services:
  fossbilling:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - fossbilling:/var/www/html
    image: fossbilling/fossbilling:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  fossbilling:

networks:  
  baota_net:  
    external: true
