services:
  nvpress:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8081"
    volumes:
      - "${APP_PATH}/data/nv-content:/usr/src/app/nv-content"
      - "${APP_PATH}/data/nv-themes:/usr/src/app/nv-themes"
      - "${APP_PATH}/data/nv-plugins:/usr/src/app/nv-plugins"
    image: pandastd/nvpress:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
