services:
  wg-easy:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    environment:
      - WG_HOST=${HOST_ADDRESS}
      - WG_PORT=${WIREGUARD_PORT}
      - PORT=${WEB_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_MTU=${WG_MTU}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE}
      - PASSWORD_HASH=${PASSWORD_HASH}
    volumes:
      - ${APP_PATH}/data:/etc/wireguard
    ports:
      - "${WIREGUARD_PORT}:${WIREGUARD_PORT}/udp"
      - "${WEB_PORT}:${WEB_PORT}/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    image: "ghcr.io/wg-easy/wg-easy:15"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
