services:
  xiaoya:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "./data:/data"
    #environment:
    #  - HTTP_PROXY=${proxy_url}
    #  - HTTPS_PROXY=${proxy_url}
    #  - no_proxy=*.aliyundrive.com
    image: xiaoyaliu/alist:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
