services:
  deeplx:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:1188"
    command: ["/app/deeplx", "-token", "${TOKEN_VAULE}"]
    image: missuo/deeplx:v1.0.7
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
