services:
  wukongim:
    container_name: ${APP_NAME}
    image: "registry.cn-shanghai.aliyuncs.com/wukongim/wukongim:v1.2"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - "${HOST_IP}:${PANEL_APP_PORT_WK_API}:5001"
      - "${HOST_IP}:${PANEL_APP_PORT_WK_TCP}:5100"
      - "${HOST_IP}:${PANEL_APP_PORT_WK_WS}:5200"
      - "${HOST_IP}:${WEB_PORT}:5300"
      - "${HOST_IP}:${PANEL_APP_PORT_WK_DEMO_SERVER}:5172"
    volumes:
      - ./wukongim:/root/wukongim
    environment:
      - WK_MODE=release
      - WK_EXTERNAL_IP=${EXTERNAL_IP}
      - WK_CONVERSATION_ON=true
      - WK_WEBHOOK_GRPCADDR=tangsengdaodaoserver:6979
      - WK_DATASOURCE_ADDR=http://tangsengdaodaoserver:8090/v1/datasource
      - WK_DATASOURCE_CHANNELINFOON=true
      - WK_TOKENAUTHON=true
    networks:
      - baota_net
    labels:
      createdBy: "bt_apps"
networks:
  baota_net:
    external: true
