services:
  mtabserver:
    image: itushan/mtab:2.6.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    user: "0"
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "./data:/app"
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
