services:
  speedtest:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - ${HOST_IP}:${WEB_PORT}:3000
      - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:3001
    image: openspeedtest/latest:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true