services:
  meowfacts:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: latest
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5000"
    labels:  
      createdBy: "bt_apps" 

networks:  
  baota_net:  
    external: true

