services:
  linkstack:
    image: linkstackorg/linkstack
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443"
    hostname: ${APP_NAME}
    environment:
      - HTTP_SERVER_NAME=${HTTP_SERVER_NAME}
      - HTTPS_SERVER_NAME=${HTTPS_SERVER_NAME}
      - SERVER_ADMIN=${SERVER_ADMIN}
      - TZ=${TIME_ZONE}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}
    volumes:
      - linkstack:/htdocs
    labels:  
      createdBy: "bt_apps"

volumes:
  linkstack:

networks:  
  baota_net:  
    external: true