services:
  flexget:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5050"
    volumes:
      - ./data/config:/config
      - ${APP_PATH}/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - FG_WEBUI_PASSWD=${WEB_PASSWORD}
    image: wiserain/flexget:3.16.12
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
