services:
  als:
    container_name: ${APP_NAME}
    restart: always
    network_mode: "host"
    environment:
      - HTTP_PORT=${WEB_PORT}
    image: wikihostinc/looking-glass-server
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

