services:
  qbittorrent:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    environment:
        - UID=1000
        - GID=1000
        - PEER_PORT=${PEER_PORT_VALUE}
        - WEB_PORT=${WEB_PORT}
    ports:
        - "${PEER_PORT_VALUE}:${PEER_PORT_VALUE}"
        - "${PEER_PORT_VALUE}:${PEER_PORT_VALUE}/udp"
        - "${WEB_PORT}:${WEB_PORT}"
    volumes:
        - "./data/.config:/data/.config"
        - "./data/.local:/data/.local"
        - "${CACHE_PATH}:/data/.cache"
        - "${DOWNLOAD_PATH}:/data/downloads"
    image: "jarylc/qbittorrent:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
   
networks:  
  baota_net:  
    external: true