services:
  syncclipboard-server:
    image: jericx/syncclipboard-server:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5033"
    volumes:
      - ${CONFIG_FILE_PATH}:/app/appsettings.json
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
