services:
  mcsm-web:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:23333"
    volumes:
      - "${APP_PATH}/data:/opt/mcsmanager/web/data"
    image: alisaqaq/mcsmanager-web:10.1.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
