services:
  zerotier-moon:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:9993/udp"
    volumes:
      - ./data:/var/lib/zerotier-one
    entrypoint:
      - /startup.sh
      - "-4"
      - ${HOST_IPV4}
      - "-6"
      - ${HOST_IPV6}
    image: seedgou/zerotier-moon:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
