services:
  audiobookshelf:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "${DATA_PATH1}:/audiobooks"
      - "${DATA_PATH2}:/podcasts"
      - "${APP_PATH}/data:/config"
      - "${DATA_PATH3}:/metadata"
    image: advplyr/audiobookshelf:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
