services:
  speedtest-x:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - WEBPORT=${WEB_PORT}
      - MAX_LOG_COUNT=${MAX_LOG_COUNT}
      - IP_SERVICE=${IP_SERVICE}
      - SAME_IP_MULTI_LOGS=${SAME_IP_MULTI_LOGS}
    image: badapple9/speedtest-x:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
