services:
  atvloadly:
    image: "bitxeno/atvloadly:v0.2.6"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "${APP_PATH}/data:/data"
      - "${DBUS_PATH}:/var/run/dbus"
      - "${AVAHI_DAEMON_PATH}:/var/run/avahi-daemon"
    privileged: ${PRIVILEGED_MODE}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
