services:
  ms365-e5-renew-x:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:1066"
    volumes:
      - ./Deploy:/app/Deploy
      - ./appdata:/app/appdata
    environment:
      - TZ=${TIME_ZONE}
    image: hanhongyong/ms365-e5-renew-x:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true