services:
  nas-tools:
    image: "hsuyelin/nas-tools:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3000"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${MEDIA_PATH}:/media"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - NASTOOL_AUTO_UPDATE=${NASTOOL_AUTO_UPDATE}
      - NASTOOL_CN_UPDATE=${NASTOOL_CN_UPDATE}
    hostname: ${HOSTNAME}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
