services:
  opentdp:
    image: rehiy/tdp-cloud:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:7800"
    volumes:
      - ./data/conf:/etc/tdp-cloud
      - ./data/data:/var/lib/tdp-cloud
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true