services:
  subconverter:
    image: tindy2013/subconverter:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:25500"
    volumes:
      - ./data:/mnt
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
