services:
  mdc-ng:
    image: "mdcng/mdc:1.11.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:9208"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${MEDIA_PATH}:${MEDIA_PATH_INTERNAL}"
      - "${MEDIA_PATH_2}:${MEDIA_PATH_INTERNAL_2}"
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
