services:
  siyuan:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:6806"
    volumes:
      - "${APP_PATH}/data:/siyuan/workspace"
    user: "1000:1000"
    command: "--workspace=/siyuan/workspace/"
    image: b3log/siyuan:v3.2.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
