services:
  twikoo:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    volumes:
      - "${APP_PATH}/data:/app/data"
    environment:
      - "TWIKOO_THROTTLE=1000"
      - "TWIKOO_PORT=8080"
    image: imaegoo/twikoo:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
