services:
  sub2sing-box:
    image: nite07/sub2sing-box:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
