services:
  lskypro:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    volumes:
      - "${APP_PATH}/data:/var/www/html/"
    ports:
      - "${HOST_IP}:${WEB_PORT}:8089"
    environment:
      - "WEB_PORT=8089"
    image: halcyonazure/lsky-pro-docker:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
