services:
  linux-command:
    image: "wcjiang/linux-command:1.20.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:3000"
    networks:
      - baota_net
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
