services:
  lrcapi:
    image: "hisatri/lrcapi:1.6.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:28883"
    volumes:
      - ${MUSIC_PATH}:/music
    environment:
      - API_AUTH=${API_AUTH}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
