services:
  dbgate:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
        - "${HOST_IP}:${WEB_PORT}:3000"
    volumes:
        - "${APP_PATH}/data:/root/.dbgate"
    image: "dbgate/dbgate:6.5.4"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true