services:
  anqicms:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8001"
    volumes:
      - anqicms-data:/app
    image: "anqicms/anqicms:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"

volumes:
  anqicms-data:
    name: anqicms-data

networks:
  baota_net:
    external: true
