services:
  dashy:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    volumes:
      - ./data/user-data/conf.yml:/app/user-data/conf.yml
      - ./data/item-icons:/app/user-data/item-icons
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    healthcheck:
     test: ['CMD', 'node', '/app/services/healthcheck']
     interval: 1m30s
     timeout: 10s
     retries: 3
     start_period: 40s
    image: lissy93/dashy:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
