services:
  firefox:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - ${HOST_IP}:${WEB_PORT}:3000
      - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:3001
    volumes:
      - "${APP_PATH}/data:/config"
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - CUSTOM_USER=${HTTP_USER}
      - PASSWORD=${HTTP_PWD}
    shm_size: ${MEM_USE}
    image: "linuxserver/firefox:1140.0.2"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true