services:
  seatable:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      #- "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - "${APP_PATH}/data:/shared"
    environment:
      - DB_HOST=${PANEL_DB_HOST}
      - DB_ROOT_PASSWD=${PANEL_DB_ROOT_PASSWORD}
      - TIME_ZONE=${TIME_ZONE}
      - SEATABLE_SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - SEATABLE_SERVER_LETSENCRYPT=false
    image: seatable/seatable-developer:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
