services:
  duplicati:
    image: "duplicati/duplicati:2.1.0.120"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8200"
    volumes:
      - ${BACKUPS_PATH}:${INTERNAL_BACKUPS_PATH}
      - ${APP_PATH}/data:/data
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
