services:
  cloudreve:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5212"
    volumes:
      - "${UPLOAD_PATH}:/cloudreve/uploads"
      - "${TMP_PATH}:/data"
      - "./data/conf.ini:/cloudreve/conf.ini"
      - "./data/cloudreve.db:/cloudreve/cloudreve.db"
      - "./data/avatar:/cloudreve/avatar"
    image: cloudreve/cloudreve:4.1.3
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
