services:
  zabbix-agent:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:10050"
    environment:
      - ZBX_HOSTNAME=${HOSTNAME}
      - ZBX_SERVER_HOST=${ZABBIX_SERVER}
      - ZBX_SERVER_PORT=${ZABBIX_SERVER_PORT}
    image: zabbix/zabbix-agent:alpine-latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: Apps

networks:
  baota_net:
    external: true
