services:
  vanblog:
    image: mereith/van-blog:v0.54.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - ${APP_PATH}/data/data/static:/app/static
      - ${APP_PATH}/data/log:/var/log
      - ${APP_PATH}/data/caddy/config:/root/.config/caddy
      - ${APP_PATH}/data/caddy/data:/root/.local/share/caddy
    environment:
      - TZ=${TIME_ZONE}
      - EMAIL=${EMAIL}
      - VAN_BLOG_CDN_URL=${VAN_BLOG_CDN_URL}
      - VAN_BLOG_WALINE_DB=${VAN_BLOG_WALINE_DB}
      - VAN_BLOG_DATABASE_URL=mongodb://${PANEL_DB_ROOT_USER}:${PANEL_DB_ROOT_PASSWORD}@${HOST_IP}:${MONGO_HOST}:27017/${MONGO_DB}?authSource=admin
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
