services:
  heimdall:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - "${APP_PATH}/data:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    image: linuxserver/heimdall:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
