services:
  dashmachine:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5000"
    volumes:
      - "${APP_PATH}/data:/dashmachine/dashmachine/user_data"
    image: rmountjoy/dashmachine:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
