services:
  cloudflared:
    image: cloudflare/cloudflared:2025.7.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    command: tunnel --no-autoupdate run --token ${CFD_TOKEN}
    labels:  
      createdBy: "bt_apps"

networks:
    baota_net:
        external: true
