services:
  sonarr:
    image: "linuxserver/sonarr:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${TV_SERIES_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - "${HOST_IP}:${WEB_PORT}:8989"
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
