services:
  vue-color-avatar:
    image: wenyang0/vue-color-avatar:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:5173"
    labels:
      createdBy: "bt_apps"
networks:
  baota_net:
    external: true