services:
  geekbench:
    image: "davidsarkany/geekbench:5"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: "no"
    stdin_open: true
    tty: true
    networks:
      - baota_net
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
