services:
  dujiaoka:
    image: "stilleshan/dujiaoka:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - ./data/env.conf:/dujiaoka/.env
      - ./data/uploads:/dujiaoka/public/uploads
      - ./data/storage:/dujiaoka/storage
    environment:
      - INSTALL=${INSTALL}
      - MODIFY=${MODIFY}
    networks:
      - baota_net
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
