services:
  homeassistant:
    container_name: ${APP_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "${APP_PATH}/data:/config"
    environment:
      - TZ=Asia/Shanghai
    image: homeassistant/home-assistant:2023.8.0.dev20230723
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
