services:
  diosic:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3177"
    volumes:
      - "${APP_PATH}/data:/data"
      - "${MUSIC_PATH}:/library"
    environment:
      - "LIB_NAME_1=${LIBRARY_NAME}"
    user: 1000:1000
    image: jinker25/diosic:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
