services:
  rsshub:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:1200"
    environment:
      - "NODE_ENV=production"
      - "CACHE_TYPE=redis"
      - "REDIS_URL=redis://:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}"
      - "PUPPETEER_WS_ENDPOINT=ws://rsshub-browserless:3000"
    image: diygod/rsshub:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    depends_on:
      - rsshub-browserless
    labels:
      createdBy: Apps

  rsshub-browserless:
    container_name: ${APP_NAME}-browserless
    restart: always
    networks:
      - baota_net
    ulimits:
      core:
        hard: 0
        soft: 0
    image: browserless/chrome:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
