services:
  xunsearch:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${INDEX_SERVER_PORT}:8383"
      - "${HOST_IP}:${SEARCH_SERVER_PORT}:8384"
    volumes:
      - ${APP_PATH}/data:/usr/local/xunsearch/data
    image: hightman/xunsearch:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
