services:
  zerotier-one:
    container_name: ${APP_NAME}
    restart: always
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./data:/var/lib/zerotier-one
    image: "zerotier/zerotier:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
