services:
  headscale:
    container_name: ${APP_NAME}
    restart: always
    networks:
      baota_net:
        ipv4_address: ${SUBNET}
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    volumes:
      - "./data/config:/etc/headscale"
      - "./data/data:/var/lib/headscale"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    command: ['headscale', 'serve']
    image: headscale/headscale:0.23.0-alpha3
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
