services:
  nezha-agent:
    image: "whoer/nezha-agent:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME} 
    restart: always
    command: --tls -s ${NZ_GRPC_URL} -p ${NZ_CLENT_SECRET} -d
    volumes:
      - /etc:/etc:ro
    network_mode: host
    labels:  
      createdBy: "bt_apps"