services:
  nginxpm:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTP1}:81"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTP2}:443"
    volumes:
      - "${APP_PATH}/data:/data"
      - "${SSL_PATH}:/etc/letsencrypt"
    image: jc21/nginx-proxy-manager:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
