services:
  sun-panel:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3002"
    volumes:
      - ${APP_PATH}/data/conf:/app/conf
      - ${APP_PATH}/data/uploads:/app/uploads
      - ${APP_PATH}/data/database:/app/database
    image: hslr/sun-panel:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
