services:
  mediawiki:
    image: "mediawiki:1.44.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - ${MEDIAWIKI_IMAGES_PATH}:/var/www/html/images
      - ${MEDIAWIKI_DATA_PATH}:${INTERNAL_DATA_PATH}
      # 以下行前添加#号表示关闭映射，可进行初始化配置生成
      - ${LOCAL_SETTINGS_PATH}:/var/www/html/LocalSettings.php
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
