services:
  ddns-go:
    container_name: ${APP_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "${APP_PATH}/data:/root"
    image: jeessy/ddns-go:v6.11.2
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"
