services:
  chinesesubfinder:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:19035"
      - "127.0.0.1:${HOST_IP}:${PANEL_APP_PORT_IMAGE}:19037"
    volumes:
      - ${APP_PATH}/data/config:/config
      - ${MEDIA_PATH}:/media
      - ${MEDIA_PATH2}:/media2
      - ${APP_PATH}/data/browser:/root/.cache/rod/browser
    environment:
      - PUID=1026
      - PGID=100
      - PERMS=true
      - TZ=Asia/Shanghai
      - UMASK=022
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
    hostname: chinesesubfinder
    image: allanpk716/chinesesubfinder:v0.55.3
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
