services:
  hasty-paste:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8000"
    volumes:
      - hpaste_data:/app/data
    environment:
      - TZ=Asia/Shanghai
    image: ghcr.io/enchant97/hasty-paste:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  hpaste_data:

networks:  
  baota_net:  
    external: true
