services:
  telegram:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:6901"
    volumes:
      - "telegram_data:/home/kasm-user"
    environment:
      - VNC_PW=${HTTP_PWD}
    shm_size: ${MEM_USE}
    tty: true
    image: kasmweb/telegram:1.17.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  telegram_data:

networks:  
  baota_net:  
    external: true
