services:
  minichat:
    image: "okhanyu/minichat:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    volumes:
      - "${CONFIG_PATH}:/app/config.yaml"
    environment:
      - TEMPLATE_NAME=${TEMPLATE_NAME}
    labels:  
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
