services:
  discuz:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - discuz_data:/var/www/html
    image: tencentci/discuz:v3.4
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  discuz_data:

networks:  
  baota_net:  
    external: true
