services:
  surveyking:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:1991"
    volumes:
      - "${APP_PATH}/data/files:/surveyking/files"
      - "${APP_PATH}/data/logs:/surveyking/logs"
    image: surveyking/surveyking:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
