services:
  kms-web:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      - "${HOST_IP}:${KMS_PORT}:1688"
    environment:
      - KMS_README_WEB=true
    image: johngong/kms:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
