services:
  mynodequery:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5000"
    volumes:
      - ./data/appsettings.json:/app/appsettings.json
    logging:
      options:
        max-size: 256MB
    image: jaydenlee2019/mynodequery:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
