services:
  hexo:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:4000"
    volumes:
      - "${APP_PATH}/data:/app"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - GIT_USER=${GIT_USERNAME}
      - GIT_EMAIL=${GIT_MAIL}
    image: bloodstar/hexo:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
