services:
  transmission:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:9091"
      - "${PEER_PORT_VALUE}:${PEER_PORT_VALUE}"
      - "${PEER_PORT_VALUE}:${PEER_PORT_VALUE}/udp"
    volumes:
      - "./data/config:/config"
      - "${DOWNLOAD_PATH}:/downloads"
      - "${WATCH_PATH}:/watch"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME= #optional
      - USER=${WEBUI_USER}
      - PASS=${WEBUI_PWD}
      - WHITELIST= #optional
      - PEERPORT=${PEER_PORT_VALUE}
      - HOST_WHITELIST= #optional
    image: linuxserver/transmission:4.0.6
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
