services:
  1panel:
    container_name: ${APP_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${APP_PATH}/data:/opt
      - /root:/root
    environment:
      - TZ=${TIME_ZONE}
    image: moelin/1panel:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
