services:
  gowebdav:
    image: 117503445/go_webdav:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    environment:
      - "dav=${DAV}"
    volumes:
      - ${APP_PATH}/data:${INNER_DATA_PATH}
      - ${DATA_PATH2}:${INNER_DATA_PATH2}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
