services:
  discussion:
    image: "kingwrcy/discussion:1.2.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:3000"
    environment:
      DATABASE_URL: "postgres://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}"
    networks:
      - baota_net
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
