services:
  alist:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5244"
    volumes:
      - "${APP_PATH}/data:/opt/alist/data"
      - "${APP_PATH}/mnt:/mnt/data"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    image: xhofe/alist:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true

