services:
  mdcx:
    image: "stainless403/mdcx-builtin-gui-base:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5800"
      - "${HOST_IP}:${VNC_PORT}:5900"
    environment:
      - TZ=${TIME_ZONE}
      - DISPLAY_WIDTH=${DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${MDCX_CONFIG_PATH}:/mdcx-config"
      - "${MDCX_CONFIG_FILE}:/app/MDCx.config"
      - "${LOGS_PATH}:/app/Log"
      - "${MEDIA_PATH}:${MEDIA_PATH_INTERNAL}"
      - "${MEDIA_PATH_2}:${MEDIA_PATH_INTERNAL_2}"
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
