services:
  iyuuplus:
    image: "iyuucn/iyuuplus:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8780"
    volumes:
      - ${IYUU_PATH}:/iyuu
      - ${APP_PATH}/data:/data
      - ${QBITTORRENT_PATH}:${INTERNAL_QBITTORRENT_PATH}
      - ${TRANSMISSION_PATH}:${INTERNAL_TRANSMISSION_PATH}
      - ${EXTERNAL_MOUNT_PATH}:${INTERNAL_MOUNT_PATH}
    stdin_open: true
    tty: true
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
