services:
  mt-photos:
    image: "mtphotos/mt-photos:1.38.1"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8063"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${UPLOAD_PATH}:/upload"
      - "${MEDIA_PATH}:${MEDIA_PATH_INTERNAL}"
      - "${MEDIA_PATH_2}:${MEDIA_PATH_INTERNAL_2}"
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
