services:
  metatube-sdk-go:
    image: "metatube/metatube-server:1.2.8"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - ${APP_PATH}/data:/var/run
    command: -dsn "postgres://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}" -port ${WEB_PORT} -db-auto-migrate -db-prepared-stmt
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
