services:
  adguardhome:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - ${HOST_IP}:${PLAIN_DNS_PORT}:53/tcp
      - ${HOST_IP}:${PLAIN_DNS_PORT}:53/udp
      - ${HOST_IP}:${DHCP_PORT1}:67/udp
      - ${HOST_IP}:${DHCP_PORT2}:68/udp
      - ${HOST_IP}:${HTTP_PORT}:80/tcp
      - ${HOST_IP}:${DOH_PORT}:443/tcp
      - ${HOST_IP}:${DOH_PORT}:443/udp
      - ${HOST_IP}:${WEB_PORT}:3000/tcp
      - ${HOST_IP}:${DOT_PORT}:853/tcp
      - ${HOST_IP}:${QUIC_PORT1}:784/udp
      - ${HOST_IP}:${DOT_PORT}:853/udp
      - ${HOST_IP}:${QUIC_PORT2}:8853/udp
      - ${HOST_IP}:${DNS_CRYPT_PORT}:5443/tcp
      - ${HOST_IP}:${DNS_CRYPT_PORT}:5443/udp
    volumes:
      - ${WORK_PATH}:/opt/adguardhome/work
      - ${CONFIG_PATH}:/opt/adguardhome/conf
    image: adguard/adguardhome:v0.107.63
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps" 

networks:  
  baota_net:  
    external: true
