services:
  domain-admin:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8000"
    volumes:
      - "${APP_PATH}/data/database:/app/database"
      - "${APP_PATH}/data/logs:/app/logs"
    image: mouday/domain-admin:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
