services:
  resilio-sync:
    image: linuxserver/resilio-sync:3.0.3
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8888"
      - "${HOST_IP}:${PANEL_APP_PORT_SYNC}:55555"
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${SYNC_PATH}:/sync
      - ${EXTERNAL_MOUNT_PATH}:${INTERNAL_MOUNT_PATH}
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
