services:
  cashbook:
    image: "dingdangdog/cashbook:4.3.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - ${APP_PATH}/data:/app/resources/data
    environment:
      - TOKEN_SALT=${TOKEN_SALT}
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVER_KEY=${SERVER_KEY}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
