services:
  code:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8443"
    volumes:
      - "${APP_PATH}/data:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD=${WEB_PASSWORD} 
      - SUDO_PASSWORD=${SUDO_PASSWORD} 
      - DEFAULT_WORKSPACE=/config/workspace
    image: linuxserver/code-server:4.101.2
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
