services:
  hertzbeat:
    container_name: ${APP_NAME}
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:1157"
    volumes:
      - "${APP_PATH}/data/data:/opt/hertzbeat/data"
      - "${APP_PATH}/data/logs:/opt/hertzbeat/logs"
    image: tancloud/hertzbeat:1.7.1
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
