services:
  onedev:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:6610"
      - "${HOST_IP}:${SSH_PORT}:6611"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${APP_PATH}/data:/opt/onedev"
    image: 1dev/server:11.6.16
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
