services:
  flarum:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8000"
    volumes:
      - "${APP_PATH}/data:/data"
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=256M
      - CLEAR_ENV=yes
      - OPCACHE_MEM_SIZE=128M
      - LISTEN_IPV6=true
      - REAL_IP_FROM=0.0.0.0/32
      - DB_HOST=${PANEL_DB_HOST}
      - DB_PORT=${FLARUM_DB_PORT}
      - DB_NAME=${PANEL_DB_NAME}
      - DB_USER=${PANEL_DB_USER}
      - DB_PASSWORD=${PANEL_DB_USER_PASSWORD}
      - DB_PREFIX=${PANEL_DB_PREFIX}
      - DB_NOPREFIX=false
      - DB_TIMEOUT=60
      - FLARUM_BASE_URL=${FLARUM_EXTERNAL_URL}
    image: crazymax/flarum:1.8.10
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: Apps
networks:
  baota_net:
    external: true
