services:
  chuanhuchat:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:7860"
    volumes:
      - ./data/history:/app/history
      - ./data/config.json:/app/config.json
    image: tuchuanhuhuhu/chuanhuchatgpt:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
