services:
  easytier:
    image: "easytier/easytier:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    network_mode: host
    privileged: ${PRIVILEGED_MODE}
    hostname: ${HOSTNAME}
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ${APP_PATH}/data:/root
    command: ${COMMAND}
    labels:
      createdBy: "bt_apps"
