services:
  sublink:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5000"
    volumes:
      - sublink_data:/app/app/db
    image: jaaksi/sublink:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  sublink_data:
    name: sublink_data

networks:  
  baota_net:  
    external: true
