services:
  lobe-chat:
    image: lobehub/lobe-chat:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3210"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_PROXY_URL=${OPENAI_PROXY_URL}
      - ACCESS_CODE=${ACCESS_CODE}
      - OPENAI_MODEL_LIST=${OPENAI_MODEL_LIST}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
