services:
  piclist:
    image: "kuingsmile/piclist:v1.9.14"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:36677"
    volumes:
      - "${APP_PATH}/data:/root/.piclist"
    command: node /usr/local/bin/picgo-server -k ${AUTH_KEY}
    labels:
      createdBy: "bt_apps"
   
networks:
  baota_net:
    external: true
