services:
  medama:
    image: "ghcr.io/medama-io/medama:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    volumes:
      - medama-data:/app/data
    labels:
      createdBy: "bt_apps"

volumes:
  medama-data:
    name: medama-data

networks:
  baota_net:
    external: true
