services:
  moments:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "moments_data:/app"
    image: drizzle2001/moments:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  moments_data:

networks:  
  baota_net:  
    external: true
