services:
  script-hub:
    image: "xream/script-hub:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${BETA_PORT}:${BETA_PORT}"
    environment:
      - PORT=${WEB_PORT}
      - BASE_URL=${BASE_URL}
      - BETA_PORT=${BETA_PORT}
      - BETA_BASE_URL=${BETA_BASE_URL}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
