services:
  act_runner:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    volumes:
      #- ${APP_PATH}/data/config.yaml:/config.yaml # 可选配置
      - ${APP_PATH}/data/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #- CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=${RUNNER_NAME}
      - GITEA_RUNNER_LABELS=${RUNNER_LABELS}
    image: gitea/act_runner:0.2.12
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
