services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8088"
    volumes:
      - "${APP_PATH}/data:/data/api/data"
    environment:
      - API_ROOT=${API_ROOT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
