services:
  joplin:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:22300"
    environment:
      - APP_BASE_URL=${JOPLIN_EXTERNAL_URL}
      - APP_PORT=22300
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DB_CLIENT=pg
    image: florider89/joplin-server:3.0.1
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
