services:
  maddymail:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${SMTP_IN_PORT}:25"
      - "${HOST_IP}:${IMAP4_PORT}:143"
      - "${HOST_IP}:${SMTP_S_PORT}:465"
      - "${HOST_IP}:${SMTP_S_PORT2}:587"
      - "${HOST_IP}:${IMAP4_PORT2}:993"
    volumes:
      - maddydata:/data
    environment:
      - MADDY_HOSTNAME=${MAIL_HOSTNAME}
      - MADDY_DOMAIN=${MAIL_DOMAIN}
    image: foxcpp/maddy:0.8.1
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  maddydata:
    external: true

networks:  
  baota_net:  
    external: true
