services:
  easynode:
    image: "chaoszhu/easynode:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8082"
    volumes:
      - ${APP_PATH}/data:/easynode/app/db
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
