services:
  frps:
    container_name: ${APP_NAME}
    restart: always
    network_mode: "host"
    volumes:
        #- "${CONFIG_FILE_PATH}:/etc/frp/frps.ini" #截止5.1.3版本使用ini
        - "${CONFIG_FILE_PATH}:/etc/frp/frps.toml"
        - "${SSL_FOLDER_PATH}:/etc/frp/ssl"
    image: "snowdreamtech/frps:0.63.0"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
