services:
  pgadmin4:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    image: dpage/pgadmin4:9.5
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  pgadmin4-data:

networks:  
  baota_net:  
    external: true
