services:
  watchtower:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - ${ENV1}
    command: ${COMMAND1}
    image: containrrr/watchtower
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
