services:
  obsidian-zh:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:6090"
      - "${HOST_IP}:${PANEL_APP_PORT_VNC}:5900"
      - "${HOST_IP}:${PANEL_APP_PORT_SSH}:22"
    volumes:
      - ${APP_PATH}/data/vaults:/vaults
    environment:
      - PASSWD=${HTTP_PWD}
      - SIZE=${DISPLAY_SIZE}
    privileged: ${PRIVILEGED_MODE}
    image: hcyxsmile/obsidian-docker:v1.0-ob1.3.5
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
