services:
  calibre-web:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8083"
    volumes:
      - "./data/config:/config"
      - "${APP_PATH}/data:/books"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    image: linuxserver/calibre-web:0.6.24
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
