services:
  searxng:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8080"
    volumes:
      - "${APP_PATH}/data:/etc/searxng"
    environment:
      - BASE_URL=${SEARXNG_EXTERNAL_URL}
    image: searxng/searxng:2023.7.1-5720844f
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
