services:
  beszel:
    image: "henrygd/beszel:0.11.1"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8090"
    volumes:
      - ${APP_PATH}/data:/beszel_data
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
