services:
  easytier:
    image: "easytier/easytier:v2.3.2"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    network_mode: host
    privileged: ${PRIVILEGED_MODE}
    hostname: ${HOSTNAME}
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ${APP_PATH}/data:/root
      - ${CONFIG_FILE_PATH}:${CONFIG_FILE_PATH_INTERNAL}
    command: ${COMMAND}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
