services:
  myip:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:18966"
    environment:
      - BING_MAP_API_KEY=${BING_MAP_API_KEY}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
      - IPINFO_API_TOKEN=${IPINFO_API_TOKEN}
    image: jason5ng32/myip:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
