services:
  easyimage:
  deploy:
    resources:
      limits:
        cpus: ${CPUS}
        memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "${APP_PATH}/data/config:/app/web/config"
      - "${APP_PATH}/data/i:/app/web/i"
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - DEBUG=false
    image: ddsderek/easyimage:v2.8.3-r1
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
