services:
  frp-panel:
    container_name: ${APP_NAME}
    restart: always
    network_mode: host
    command: ${COMMAND_LINE}
    image: vaalacat/frp-panel:v0.1.22
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"
