services:
  vps-stock-monitor:
    image: "vpslog/vps-stock-monitor:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:5000"
    volumes:
      - "${APP_PATH}/data:/app/data"
    environment:
      - PROXY_HOST=${PROXY_HOST}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true