services:
  grafana:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3000"
    volumes:
      - ./data:/var/lib/grafana
    user: '0'
    image: grafana/grafana:12.0.2
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
