services:
  dosgame:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:262"
    volumes:
      - dosgame_data:/app/static/games
    image: oldiy/dosgame-web-docker:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

volumes:
  dosgame_data:

networks:  
  baota_net:  
    external: true
