services:
  sunshine:
    image: "lizardbyte/sunshine:latest-ubuntu-24.04"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    devices:
      - /dev/dri/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_PATH}/data:/config
    ports:
      - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:47990
      - "${HOST_IP}:${PANEL_APP_PORT_TCP}:47984-47989/tcp"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTP2}:48010"
      - "${HOST_IP}:${PANEL_APP_PORT_UDP}:47998-48000/udp"
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true