services:
  reubah:
    image: "ghcr.io/dendianugerah/reubah:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
        - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - "${APP_PATH}/data/tmp:/app/tmp"
      - "${APP_PATH}/data/doc-temp:/tmp"
    environment:
      - PORT=${WEB_PORT}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
