services:
  frp-panel-master:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:9000"
      - "${HOST_IP}:${PANEL_APP_PORT_RPC}:9001"
    volumes:
      - "${APP_PATH}/data:/data"
    environment:
      - APP_GLOBAL_SECRET=${APP_GLOBAL_SECRET}
      - MASTER_RPC_HOST=${MASTER_RPC_HOST}
    image: vaalacat/frp-panel:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
