services:
  neko:
    image: ${IMAGE_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    shm_size: "${MEM_USE}"
    ports:
      - "${WEB_PORT}:${NEKO_BIND}"
      - "${NEKO_EPR}:${NEKO_EPR}/udp"
    volumes:
        - "${DOWNLOAD_PATH}:${NEKO_FILE_TRANSFER_PATH}"
    environment:
      - NEKO_SCREEN=${NEKO_SCREEN}
      - NEKO_PASSWORD=${NEKO_PASSWORD}
      - NEKO_PASSWORD_ADMIN=${NEKO_PASSWORD_ADMIN}
      - NEKO_EPR=${NEKO_EPR}
      - NEKO_ICELITE=${NEKO_ICELITE}
      - NEKO_CONTROL_PROTECTION=${NEKO_CONTROL_PROTECTION}
      - NEKO_IMPLICIT_CONTROL=${NEKO_IMPLICIT_CONTROL}
      - NEKO_LOCKS=${NEKO_LOCKS}
      - NEKO_NAT1TO1=${NEKO_NAT1TO1}
      - NEKO_IPFETCH=${NEKO_IPFETCH}
      - NEKO_ICESERVER=${NEKO_ICESERVER}
      - NEKO_ICESERVERS=${NEKO_ICESERVERS}
      - NEKO_VIDEO_CODEC=${NEKO_VIDEO_CODEC}
      - NEKO_VIDEO_BITRATE=${NEKO_VIDEO_BITRATE}
      - NEKO_MAX_FPS=${NEKO_MAX_FPS}
      - NEKO_HWENC=${NEKO_HWENC}
      - NEKO_AUDIO_CODEC=${NEKO_AUDIO_CODEC}
      - NEKO_AUDIO_BITRATE=${NEKO_AUDIO_BITRATE}
      - NEKO_BROADCAST_PIPELINE=${NEKO_BROADCAST_PIPELINE}
      - NEKO_BROADCAST_URL=${NEKO_BROADCAST_URL}
      - NEKO_BROADCAST_AUTOSTART=${NEKO_BROADCAST_AUTOSTART}
      - NEKO_BIND=:${NEKO_BIND}
      - NEKO_CERT=${NEKO_CERT}
      - NEKO_KEY=${NEKO_KEY}
      - NEKO_PROXY=${NEKO_PROXY}
      - NEKO_PATH_PREFIX=${NEKO_PATH_PREFIX}
      - NEKO_CORS=${NEKO_CORS}
      - NEKO_FILE_TRANSFER_ENABLED=${NEKO_FILE_TRANSFER_ENABLED}
      - NEKO_FILE_TRANSFER_PATH=${NEKO_FILE_TRANSFER_PATH}
      - NEKO_DISPLAY=${NEKO_DISPLAY}
      - NEKO_DEVICE=${NEKO_DEVICE}
      - NEKO_STATIC=${NEKO_STATIC}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
