services:
  h5ai:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "${APP_PATH}/data:/h5ai"
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - HTPASSWD=${AUTH_ENABLE}
      - HTPASSWD_USER=${USER}
      - HTPASSWD_PW=${PASSWORD}
    tty: true
    image: bin20088/h5ai:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
