services:
  chatgpt-next-web:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3000"
    environment:
      - "OPENAI_API_KEY=${API_KEY}"
      - "CODE=${SECRET_KEY}"
      - "PROXY_URL=${PROXY}"
      - "BASE_URL=${API_BASE_URL}"
    image: yidadaa/chatgpt-next-web:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
