services:
  deluge:
    image: "linuxserver/deluge:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - "${HOST_IP}:${WEB_PORT}:8112"
      - "${DELUGE_PEER_PORT}:${DELUGE_PEER_PORT}"
      - "${DELUGE_PEER_PORT}:${DELUGE_PEER_PORT}/udp"
      - "${DELUGE_PORT_RPC}:${DELUGE_PORT_RPC}"
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
