services:
  filebrowser:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - "${APP_PATH}/mnt:/srv"
      - "./data/database.db:/database.db"
      - "./data/.filebrowser.json:/.filebrowser.json"
    user: "${UID}:${GID}"
    image: filebrowser/filebrowser:v2.36.1
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
