services:
  happy-chatgpt:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:3000"
    environment:
      - "OPENAI_API_KEY=${API_KEY}"
      - "HTTPS_PROXY=${HTTPS_PROXY}"
      - "OPENAI_API_BASE_URL=${API_BASE_URL}"
      - "HEAD_SCRIPTS=${HEAD_SCRIPTS_VAULE}"
      - "PUBLIC_SECRET_KEY=${PUBLIC_SECRET_KEY_VAULE}"
      - "SITE_PASSWORD=${SECRET_KEY}"
      - "OPENAI_API_MODEL=${API_MODEL}"
    image: ddiu8081/chatgpt-demo:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
