services:
  webos:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:8088"
    volumes:
      - "${APP_PATH}/data/rootPath:/webos/api/rootPath"
      - "${APP_PATH}/data/apps:/webos/web/apps"
    tty: true
    image: fs185085781/webos:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
