services:
  syncthing:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${DATA_PATH_APP_CONFIG}:/config
      - ${DATA_PATH_DATA1}:/data1
      - ${DATA_PATH_DATA2}:/data2
    ports:
      - ${HOST_IP}:${WEB_PORT}:8384
      - ${HOST_IP}:${SYNCTHING_PORT}:22000/tcp
      - ${HOST_IP}:${SYNCTHING_PORT}:22000/udp
      - ${HOST_IP}:${SYNCTHING_PORT_EXTRA_UDP}:21027/udp
    image: linuxserver/syncthing:1.30.0
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
