services:
  docker-hoster:
    image: "solipsist01/docker-hoster:latest"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    volumes:
      - ${DOCKER_SOCK_PATH}:/tmp/docker.sock
      - ${HOSTS_PATH}:/tmp/hosts
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true
