services:
  nextcloud:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - "${APP_PATH}/data/config:/config"
      - "${APP_PATH}/data/data:/data"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    image: linuxserver/nextcloud:31.0.6
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
