services:
  cook:
    image: yunyoujun/cook:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    tty: true
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
