services:
  nginx-ui:
    container_name: ${APP_NAME}
    restart: always
    networks:
      - baota_net
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
      - "${HOST_IP}:${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - ${APP_PATH}/data/nginx:/etc/nginx
      - ${APP_PATH}/data/nginx-ui:/etc/nginx-ui
      - ${WEB_PATH}:/var/www
    environment:
      - TZ=Asia/Shanghai
    image: uozi/nginx-ui:v2.0.0-beta.3
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:  
      createdBy: "bt_apps"

networks:  
  baota_net:  
    external: true
